before_script:
  - hostname
  - whoami
  - pwd
  - ls -la
  - docker --version

stages:
   - build
   - test
   - coverage
   - deploy
   - deploy_stable
  # - test-deployment
   
build:
  tags:
     - ece651
     - host-server
  stage: build
  script: docker build --build-arg LOCAL_USER_ID=`id -u`  --tag citest .

test:
  tags:
     - ece651
  stage: test
  script: scripts/run-tests-in-docker.sh
  artifacts:
    paths:
      - coverage
      
pages:
 stage: coverage
 tags:
     - ece651
 dependencies:
   - test
 script:
   - mv coverage public/
 artifacts:
   paths:
     - public

deploy:
 tags:
   - ece651
 stage: deploy
 script: ./scripts/redeploy.sh


deploy_stable:
 tags:
   - host-server
 stage: deploy
 script: ./scripts/redeploy.sh
 only:
   refs:
     - master

#test-deployment:
 #tags:
   #- host-server
 #stage: test-deployment
 #dependencies:
  # - deploy
 #script: ./scripts/test-deployment.sh
